// Copyright (c) 2026 Paul Carver
// SPDX-License-Identifier: Apache-2.0

using System.Net;
using System.Text;
using Microsoft.Extensions.Logging.Abstractions;
using PaulTechGuy.MQ.Domain;
using Shouldly;
using Xunit;

namespace PaulTechGuy.MQ.Folio.Tests;

/// <summary>
/// The one thing in Marqora that goes to the network, against a listener on loopback.
///
/// Nothing here reaches the internet, and that is a property worth stating out loud rather than
/// leaving to chance: a test suite that quietly depended on a real host would be an embarrassing
/// thing to own in this feature of all features. Every address below is 127.0.0.1 on a port the
/// operating system just handed out.
///
/// What is being asserted is mostly refusal. The happy path is one test; the rest are the ways a
/// site can answer that must not end up inside somebody's Folio.
/// </summary>
public sealed class FolioFetcherTests : IDisposable
{
    private readonly HttpListener _listener = new();
    private readonly string _prefix;
    private readonly string _scratch = Path.Combine(
        Path.GetTempPath(), "marqora-fetch-tests", Guid.NewGuid().ToString("n"));

    private Func<HttpListenerContext, Task> _respond = _ => Task.CompletedTask;

    public FolioFetcherTests()
    {
        int port = FreePort();

        _prefix = $"http://127.0.0.1:{port}/";
        _listener.Prefixes.Add(_prefix);
        _listener.Start();

        _ = Task.Run(async () =>
        {
            while (_listener.IsListening)
            {
                HttpListenerContext context;

                try
                {
                    context = await _listener.GetContextAsync();
                }
                catch (Exception ex) when (ex is HttpListenerException or ObjectDisposedException)
                {
                    return;
                }

                try
                {
                    await _respond(context);
                }
                catch (Exception ex) when (ex is HttpListenerException or ObjectDisposedException)
                {
                    // The client gave up first, which several of these tests arrange on purpose.
                }
            }
        });
    }

    [Fact]
    public async Task A_picture_that_comes_back_is_saved_and_named_from_its_address()
    {
        Serve(context => Png(context, 8, 8));

        FolioFetchResult result = await FetchAsync("chart.png");

        result.Failures.ShouldBeEmpty();
        string saved = result.Files.Values.ShouldHaveSingleItem();

        Path.GetFileName(saved).ShouldBe("chart.png");
        File.Exists(saved).ShouldBeTrue();
    }

    [Fact]
    public async Task A_jpeg_whose_size_is_not_in_its_first_bytes_is_still_a_picture()
    {
        // The Wikimedia case, reduced. A JPEG keeps its dimensions in a marker that can sit
        // kilobytes into the file, so a check that demanded a measurable size rejected a
        // perfectly good picture. What is being asserted is that the format is what decides,
        // not whether anything could be measured.
        byte[] jpeg = new byte[8192];

        jpeg[0] = 0xFF;
        jpeg[1] = 0xD8;
        jpeg[2] = 0xFF;
        jpeg[3] = 0xE0;

        Serve(context => Body(context, "image/jpeg", jpeg));

        FolioFetchResult result = await FetchAsync("photo.jpg");

        result.Failures.ShouldBeEmpty();
        result.Files.ShouldHaveSingleItem();
    }

    [Fact]
    public async Task An_svg_that_opens_with_a_declaration_and_a_comment_is_still_a_picture()
    {
        Serve(context => Body(
            context,
            "image/svg+xml",
            Encoding.UTF8.GetBytes(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                + "<!-- Generated by something that likes to say so -->\n"
                + "<svg xmlns=\"http://www.w3.org/2000/svg\"></svg>")));

        FolioFetchResult result = await FetchAsync("badge.svg");

        result.Failures.ShouldBeEmpty();
        result.Files.ShouldHaveSingleItem();
    }

    [Fact]
    public async Task An_xml_document_that_is_not_an_svg_is_refused()
    {
        // The opposite mistake to the one above: accepting anything that opens with "<?xml"
        // would let a feed or a sitemap into somebody's Folio as a picture.
        Serve(context => Body(
            context,
            "image/svg+xml",
            Encoding.UTF8.GetBytes("<?xml version=\"1.0\"?><rss version=\"2.0\"></rss>")));

        FolioFetchResult result = await FetchAsync("feed.svg");

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldHaveSingleItem().Message.ShouldContain("was not a picture");
    }

    [Fact]
    public async Task A_page_served_where_a_picture_was_asked_for_is_refused()
    {
        // The sign-in page case. Sniffed from the bytes, never trusted from the content type,
        // so a site cannot put HTML inside a Folio by labelling it image/png.
        Serve(context => Body(context, "image/png", Encoding.UTF8.GetBytes("<html>Sign in</html>")));

        FolioFetchResult result = await FetchAsync("chart.png");

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldHaveSingleItem().Message.ShouldContain("was not a picture");
    }

    [Fact]
    public async Task An_error_from_the_site_is_reported_with_its_number()
    {
        Serve(context =>
        {
            context.Response.StatusCode = 503;
            context.Response.Close();

            return Task.CompletedTask;
        });

        FolioFetchResult result = await FetchAsync("chart.png");

        result.Files.ShouldBeEmpty();

        FolioWarning failure = result.Failures.ShouldHaveSingleItem();
        failure.Kind.ShouldBe(FolioWarningKind.RemoteImageFailed);
        failure.Message.ShouldContain("503");
    }

    [Fact]
    public async Task A_redirect_that_leaves_the_web_is_refused()
    {
        // The obvious game: answer the picture request with "it is over there", pointing at the
        // local disk. Checked on every hop, because the first hop is the only one the author saw.
        Serve(context =>
        {
            context.Response.StatusCode = 302;
            context.Response.Headers["Location"] = "file:///C:/Windows/win.ini";
            context.Response.Close();

            return Task.CompletedTask;
        });

        FolioFetchResult result = await FetchAsync("chart.png");

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldHaveSingleItem().Message.ShouldContain("does not point at the web");
    }

    [Fact]
    public async Task A_redirect_within_the_web_is_followed()
    {
        Serve(async context =>
        {
            if (context.Request.Url?.AbsolutePath == "/moved.png")
            {
                context.Response.StatusCode = 302;
                context.Response.Headers["Location"] = _prefix + "real.png";
                context.Response.Close();

                return;
            }

            await Png(context, 4, 4);
        });

        FolioFetchResult result = await FetchAsync("moved.png");

        result.Failures.ShouldBeEmpty();
        result.Files.ShouldHaveSingleItem();
    }

    [Fact]
    public async Task A_body_larger_than_the_cap_is_refused_while_it_is_still_arriving()
    {
        // No content length, and far more than the cap. The point is that the refusal happens
        // during the read rather than after it, so a lying or absent length cannot fill a disk.
        Serve(async context =>
        {
            context.Response.ContentType = "image/png";
            context.Response.SendChunked = true;

            byte[] block = new byte[512 * 1024];

            for (int i = 0; i < 64; i++)
            {
                await context.Response.OutputStream.WriteAsync(block);
            }

            context.Response.Close();
        });

        FolioFetchResult result = await FetchAsync("huge.png");

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldHaveSingleItem().Message.ShouldContain("larger than a picture");
    }

    [Fact]
    public async Task An_svg_is_recognized_even_though_it_has_no_binary_header()
    {
        Serve(context => Body(
            context,
            "image/svg+xml",
            Encoding.UTF8.GetBytes("<svg xmlns=\"http://www.w3.org/2000/svg\"></svg>")));

        FolioFetchResult result = await FetchAsync("badge.svg");

        result.Failures.ShouldBeEmpty();
        result.Files.ShouldHaveSingleItem();
    }

    [Fact]
    public async Task One_address_named_by_two_documents_is_fetched_once()
    {
        int hits = 0;

        Serve(context =>
        {
            Interlocked.Increment(ref hits);

            return Png(context, 8, 8);
        });

        var fetcher = new FolioFetcher(NullLogger<FolioFetcher>.Instance, "test");

        FolioFetchResult result = await fetcher.FetchAsync(
            [Image(_prefix + "logo.png", "one.md"), Image(_prefix + "logo.png", "two.md")],
            _scratch,
            cancellationToken: TestContext.Current.CancellationToken);

        result.Files.ShouldHaveSingleItem();
        hits.ShouldBe(1);
    }

    [Fact]
    public async Task Nothing_is_thrown_when_the_site_is_not_there_at_all()
    {
        // The share that calls this has no cancellation and catches only IO exceptions, so a
        // throw from here would take the whole export down. Refusing to throw is the contract.
        _listener.Stop();

        var fetcher = new FolioFetcher(NullLogger<FolioFetcher>.Instance, "test");

        FolioFetchResult result = await fetcher.FetchAsync(
            [Image(_prefix + "gone.png", "one.md")],
            _scratch,
            cancellationToken: TestContext.Current.CancellationToken);

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldHaveSingleItem().Kind.ShouldBe(FolioWarningKind.RemoteImageFailed);
    }

    [Fact]
    public async Task Nothing_is_fetched_when_there_is_nothing_to_fetch()
    {
        var fetcher = new FolioFetcher(NullLogger<FolioFetcher>.Instance, "test");

        FolioFetchResult result = await fetcher.FetchAsync(
            [],
            _scratch,
            cancellationToken: TestContext.Current.CancellationToken);

        result.Files.ShouldBeEmpty();
        result.Failures.ShouldBeEmpty();

        // Not even a folder: asking for nothing should leave nothing behind.
        Directory.Exists(_scratch).ShouldBeFalse();
    }

    private Task<FolioFetchResult> FetchAsync(string file)
    {
        var fetcher = new FolioFetcher(NullLogger<FolioFetcher>.Instance, "test");

        return fetcher.FetchAsync(
            [Image(_prefix + file, "guide.md")],
            _scratch,
            cancellationToken: TestContext.Current.CancellationToken);
    }

    private static FolioRemoteImage Image(string url, string document) => new()
    {
        Url = url,
        DocumentPath = Path.Combine(Path.GetTempPath(), document),
        Line = 0,
    };

    private void Serve(Func<HttpListenerContext, Task> respond) => _respond = respond;

    private static Task Png(HttpListenerContext context, byte width, byte height)
    {
        // The eight-byte signature plus an IHDR carrying real dimensions: enough for the header
        // reader to accept it as a picture, which is all these tests need it to be.
        byte[] png =
        [
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
            0x00, 0x00, 0x00, width, 0x00, 0x00, 0x00, height,
            0x08, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ];

        return Body(context, "image/png", png);
    }

    private static async Task Body(HttpListenerContext context, string type, byte[] bytes)
    {
        context.Response.ContentType = type;
        context.Response.ContentLength64 = bytes.Length;

        await context.Response.OutputStream.WriteAsync(bytes);

        context.Response.Close();
    }

    private static int FreePort()
    {
        var probe = new System.Net.Sockets.TcpListener(IPAddress.Loopback, 0);

        probe.Start();
        int port = ((IPEndPoint)probe.LocalEndpoint).Port;
        probe.Stop();

        return port;
    }

    public void Dispose()
    {
        try
        {
            _listener.Close();
        }
        catch (ObjectDisposedException)
        {
            // Stopped by a test on purpose.
        }

        try
        {
            if (Directory.Exists(_scratch))
            {
                Directory.Delete(_scratch, recursive: true);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Temp files are not worth failing a test over.
        }
    }
}
